[package]
name = "tauri-plugin-tsmanager"
version = "0.1.0"
authors = [ "You" ]
description = ""
edition = "2021"
rust-version = "1.77.2"
exclude = ["/examples", "/webview-dist", "/webview-src", "/node_modules"]
links = "tauri-plugin-tsmanager"

[dependencies]
tauri = { version = "2.0.0", features = [ "tray-icon" ] }
serde = "1.0"
thiserror = "2"
libc = "0.2.167"
curl = "0.4.47"
tokio = { version = "1.42.0", features = ["full"] }
dirs = "5.0.1"
#zip = "2.2.1"
zip = "0.5.13"
whoami = "1.5.2"
glob = "0.3.1"
sysinfo = "0.26.9"
image = "0.24.9"
bardecoder = "0.5.0"
winapi = { version = "0.3.9", features = ["winnt", "processthreadsapi", "winbase"] }
elevated-command = "1.1"

[build-dependencies]
tauri-plugin = { version = "2.0.2", features = ["build"] }
